# Generated by Django 5.2.7 on 2025-11-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(choices=[('gpay', 'Google Pay'), ('paytm', 'Paytm'), ('phonepe', 'PhonePe'), ('upi', 'UPI')], default='upi', max_length=20),
        ),
    ]
