# Generated by Django 5.2.7 on 2025-11-22 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_donation_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='payment_method',
        ),
    ]
